export const mdlmPiTestFiles = [
  "packages/mdlm-pi/test/cli-process.test.ts",
  "packages/mdlm-pi/test/git-publisher.test.ts",
  "packages/mdlm-pi/test/live-integration.test.ts",
  "packages/mdlm-pi/test/mdlm-client.test.ts",
  "packages/mdlm-pi/test/operator-io.test.ts",
  "packages/mdlm-pi/test/operational-failure.test.ts",
  "packages/mdlm-pi/test/pi-assignment-runner.test.ts",
  "packages/mdlm-pi/test/run-controller.test.ts",
  "packages/mdlm-pi/test/run-journal.test.ts",
  "packages/mdlm-pi/test/run-lock.test.ts",
];

// PR files run in both gates; release files run only in release qualification
// unless the PR gate names one as a diff-focused regression. This source list is
// exhaustive so verification can detect missing, duplicate, and stale entries.
export const rootTestQualificationManifest = Object.freeze([
  { file: "test/requirement-trace-inspection.test.ts", qualificationGate: "pr" },
  { file: "test/source-scopes.test.ts", qualificationGate: "pr" },
  { file: "test/requirement-trace.test.ts", qualificationGate: "pr" },
  { file: "test/load-process-package.test.ts", qualificationGate: "pr" },
  { file: "test/process-package-cases.test.ts", qualificationGate: "pr" },
  { file: "test/mdlm-assignment.test.ts", qualificationGate: "release" },
  { file: "test/proportional-distinct-context-phase-2-public.test.ts", qualificationGate: "release" },
  { file: "test/phase-3-component-definition-public.test.ts", qualificationGate: "release" },
  { file: "test/phase-decomposition-parents-public.test.ts", qualificationGate: "release" },
  { file: "test/phase-5-formal-environment-public.test.ts", qualificationGate: "pr" },
  { file: "test/gate-rejected-candidate-correction-public.test.ts", qualificationGate: "pr" },
  { file: "test/formal-ver-review-correction-public.test.ts", qualificationGate: "pr" },
  { file: "test/verification-run-projection-public.test.ts", qualificationGate: "pr" },
  { file: "test/dependency-changes.test.ts", qualificationGate: "pr" },
  { file: "test/dwp-completion-public.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-phase.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-scoped-obligation.test.ts", qualificationGate: "pr" },
  { file: "test/load-scenario-participation.test.ts", qualificationGate: "pr" },
  { file: "test/mdlm-assignment-state.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-clean-onboarding-transaction.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-cli-output.test.ts", qualificationGate: "pr" },
  { file: "test/mdlm-command-application.test.ts", qualificationGate: "pr" },
  { file: "test/mdlm-init.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-lifecycle.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-pilot-assessment.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-process-expression.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-process-migration.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-repository-inspection.test.ts", qualificationGate: "release" },
  { file: "test/mdlm-schema.test.ts", qualificationGate: "release" },
  { file: "test/operator-outcome.test.ts", qualificationGate: "release" },
  { file: "test/atomic-review-submit.test.ts", qualificationGate: "pr" },
  { file: "test/atomic-review-liveness.test.ts", qualificationGate: "pr" },
  { file: "test/same-response-payload-reference.test.ts", qualificationGate: "pr" },
  { file: "test/proportional-phase-2-public.test.ts", qualificationGate: "pr" },
  { file: "test/selected-package-cache.test.ts", qualificationGate: "release" },
  { file: "test/evaluate-bootstrap-participation.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-lifecycle.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-obligation-history.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-review-flow.test.ts", qualificationGate: "pr" },
  { file: "test/environment-review-correction-identity.test.ts", qualificationGate: "pr" },
  { file: "test/phase-1-review-routing.test.ts", qualificationGate: "pr" },
  { file: "test/phase-1-pilot-chain.test.ts", qualificationGate: "pr" },
  { file: "test/ver-contextual-review-packet.test.ts", qualificationGate: "pr" },
  { file: "test/product-acceptance-completion.test.ts", qualificationGate: "pr" },
  { file: "test/pilot-art-result-correction-public.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-shared-system-change.test.ts", qualificationGate: "pr" },
  { file: "test/evaluate-system-decomposition.test.ts", qualificationGate: "pr" },
  { file: "test/initial-product-intent-selectors.test.ts", qualificationGate: "pr" },
  { file: "test/kernel-capability.test.ts", qualificationGate: "pr" },
  { file: "test/cutover-corpus.test.ts", qualificationGate: "pr" },
  { file: "test/pi-operator-instructions.test.ts", qualificationGate: "pr" },
  { file: "test/resolve-type.test.ts", qualificationGate: "pr" },
  { file: "test/release-candidate-gate.test.ts", qualificationGate: "pr" },
  { file: "test/selector-memoization.test.ts", qualificationGate: "pr" },
  { file: "test/textual-expression.test.ts", qualificationGate: "pr" },
].map((entry) => Object.freeze(entry)));
const qualificationGateByFile = new Map(
  rootTestQualificationManifest.map((entry) => [entry.file, entry.qualificationGate]),
);

// Durations are the latest selected successful focused observations. They
// include focused Vitest startup and remain estimates, not p95s.
const rootTestRuntimeManifest = [
  { file: "test/load-process-package.test.ts", runtimeClass: "process-package-heavy", weight: 3, measuredDurationMs: 66_137 },
  { file: "test/process-package-cases.test.ts", runtimeClass: "process-package-heavy", weight: 3, measuredDurationMs: 7_220 },
  { file: "test/mdlm-assignment.test.ts", runtimeClass: "assignment-publication-heavy", weight: 3, measuredDurationMs: 53_780 },
  { file: "test/proportional-distinct-context-phase-2-public.test.ts", runtimeClass: "process-repository-heavy", weight: 1, measuredDurationMs: 27_558 },
  { file: "test/phase-3-component-definition-public.test.ts", runtimeClass: "process-repository-heavy", weight: 1, measuredDurationMs: 79_500 },
  { file: "test/phase-decomposition-parents-public.test.ts", runtimeClass: "process-repository-heavy", weight: 1, measuredDurationMs: 35_900 },
  { file: "test/phase-5-formal-environment-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 25_437 },
  { file: "test/gate-rejected-candidate-correction-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 5_000 },
  { file: "test/formal-ver-review-correction-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 23_000 },
  { file: "test/verification-run-projection-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 16_310 },

  { file: "test/dependency-changes.test.ts", runtimeClass: "canonical-fixture-filler", weight: 1, measuredDurationMs: 9_352 },
  { file: "test/dwp-completion-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 12_610 },
  { file: "test/evaluate-phase.test.ts", runtimeClass: "canonical-evaluator-safe", weight: 1, measuredDurationMs: 8_883 },
  { file: "test/evaluate-scoped-obligation.test.ts", runtimeClass: "canonical-evaluator-safe", weight: 1, measuredDurationMs: 8_019 },
  { file: "test/load-scenario-participation.test.ts", runtimeClass: "canonical-evaluator-safe", weight: 1, measuredDurationMs: 53_552 },
  { file: "test/mdlm-assignment-state.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 44_059 },
  { file: "test/mdlm-clean-onboarding-transaction.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 58_206 },
  { file: "test/mdlm-cli-output.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 4_870 },
  { file: "test/mdlm-command-application.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 63_686 },
  { file: "test/mdlm-init.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 55_478 },
  { file: "test/mdlm-lifecycle.test.ts", runtimeClass: "repository-public-fragile", weight: 1, measuredDurationMs: 30_161 },
  { file: "test/mdlm-pilot-assessment.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 15_950 },
  { file: "test/mdlm-process-expression.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 47_352 },
  { file: "test/mdlm-process-migration.test.ts", runtimeClass: "repository-public-fragile", weight: 1, measuredDurationMs: 47_070 },
  { file: "test/mdlm-repository-inspection.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 25_853 },
  { file: "test/mdlm-schema.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 33_817 },
  { file: "test/operator-outcome.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 51_114 },
  { file: "test/atomic-review-submit.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 15_190 },
  { file: "test/atomic-review-liveness.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 1_970 },
  { file: "test/same-response-payload-reference.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 4_400 },
  // 101,498 ms focused observation plus the explicit 3,600 ms cleanup-contract increase.
  { file: "test/proportional-phase-2-public.test.ts", runtimeClass: "canonical-fixture-filler", weight: 1, measuredDurationMs: 2_378 },
  { file: "test/selected-package-cache.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 22_915 },

  { file: "test/evaluate-bootstrap-participation.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 4_054 },
  { file: "test/evaluate-lifecycle.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_185 },
  { file: "test/evaluate-obligation-history.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 3_316 },
  { file: "test/evaluate-review-flow.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_501 },
  { file: "test/environment-review-correction-identity.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 13_990 },
  { file: "test/phase-1-review-routing.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 1_100 },
  { file: "test/phase-1-pilot-chain.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 4_000 },
  { file: "test/ver-contextual-review-packet.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 7_560 },
  { file: "test/product-acceptance-completion.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 893 },
  { file: "test/pilot-art-result-correction-public.test.ts", runtimeClass: "process-repository-safe", weight: 1, measuredDurationMs: 12_000 },
  { file: "test/evaluate-shared-system-change.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 3_154 },
  { file: "test/evaluate-system-decomposition.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_761 },
  { file: "test/initial-product-intent-selectors.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 4_686 },
  { file: "test/kernel-capability.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 25_272 },
  { file: "test/cutover-corpus.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 168 },
  { file: "test/pi-operator-instructions.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 978 },
  { file: "test/resolve-type.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 6_242 },
  { file: "test/release-candidate-gate.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_000 },
  { file: "test/selector-memoization.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_427 },
  { file: "test/textual-expression.test.ts", runtimeClass: "cheap-in-process", weight: 1, measuredDurationMs: 2_441 },
];

export const rootTestManifest = Object.freeze(rootTestRuntimeManifest.map((entry) => Object.freeze({
  ...entry,
  qualificationGate: qualificationGateByFile.get(entry.file),
})));

export const rootVitestSuites = [
  "process-package-heavy",
  "assignment-publication-heavy",
  "baseline-integrity-heavy",
  "process-repository-heavy",
  "repository-public-fragile",
  "process-repository-safe",
  "canonical-evaluator-safe",
  "canonical-fixture-filler",
  "cheap-in-process",
].map((id) => ({
  id,
  weight: rootTestManifest.find((entry) => entry.runtimeClass === id)?.weight,
  files: rootTestManifest
    .filter((entry) => entry.runtimeClass === id)
    .map((entry) => entry.file),
}));

// Compatibility export for Vitest configuration and tooling that need the
// complete root-suite membership rather than its resource schedule.
export const testFiles = rootTestManifest.map((entry) => entry.file);
