export const mdlmPiTestFiles = [
  "packages/mdlm-pi/test/cli-process.test.ts",
  "packages/mdlm-pi/test/git-publisher.test.ts",
  "packages/mdlm-pi/test/live-integration.test.ts",
  "packages/mdlm-pi/test/mdlm-client.test.ts",
  "packages/mdlm-pi/test/pi-assignment-runner.test.ts",
  "packages/mdlm-pi/test/run-controller.test.ts",
  "packages/mdlm-pi/test/run-journal.test.ts",
  "packages/mdlm-pi/test/run-lock.test.ts",
];

export const rootVitestSuites = [
  {
    id: "process-repository-heavy",
    maxWorkers: 2,
    files: [
      "test/load-process-package.test.ts",
      "test/mdlm-baseline-inspection.test.ts",
      "test/mdlm-assignment.test.ts",
      "test/proportional-distinct-context-phase-2-public.test.ts",
    ],
  },
  {
    id: "standard-resource",
    maxWorkers: 4,
    files: [
      "test/dependency-changes.test.ts",
      "test/evaluate-phase.test.ts",
      "test/evaluate-scoped-obligation.test.ts",
      "test/initial-product-intent-resolution.test.ts",
      "test/initial-product-intent-route.test.ts",
      "test/kernel-capability.test.ts",
      "test/load-scenario-participation.test.ts",
      "test/mdlm-assignment-state.test.ts",
      "test/mdlm-clean-onboarding-transaction.test.ts",
      "test/mdlm-clean-pilot-contract.test.ts",
      "test/mdlm-command-application.test.ts",
      "test/mdlm-init.test.ts",
      "test/mdlm-lifecycle.test.ts",
      "test/mdlm-pilot-assessment.test.ts",
      "test/mdlm-process-expression.test.ts",
      "test/mdlm-process-migration.test.ts",
      "test/mdlm-repository-inspection.test.ts",
      "test/mdlm-review-assignment.test.ts",
      "test/mdlm-schema.test.ts",
      "test/operator-outcome.test.ts",
      "test/phase-0-corrected-gate-route.test.ts",
      "test/phase-0-intent-candidate-currentness-route.test.ts",
      "test/phase-1-hardening-routes.test.ts",
      "test/phase-2-hardening-routes.test.ts",
      "test/resolve-type.test.ts",
      "test/scenario-policy-assets.test.ts",
      "test/selected-package-cache.test.ts",
    ],
  },
  {
    id: "cheap-in-process",
    maxWorkers: 4,
    files: [
      "test/change-and-pilot-hardening-routes.test.ts",
      "test/evaluate-bootstrap-participation.test.ts",
      "test/evaluate-lifecycle.test.ts",
      "test/evaluate-obligation-history.test.ts",
      "test/evaluate-review-flow.test.ts",
      "test/evaluate-shared-system-change.test.ts",
      "test/evaluate-system-decomposition.test.ts",
      "test/initial-product-intent-selectors.test.ts",
      "test/phase-0-hardening-routes.test.ts",
      "test/phase-1-route-contracts.test.ts",
      "test/phase-hardening-domain-contracts.test.ts",
      "test/phase-hardening-matrix.test.ts",
      "test/pi-operator-instructions.test.ts",
      "test/proportional-phase-2-public.test.ts",
      "test/selector-memoization.test.ts",
      "test/textual-expression.test.ts",
    ],
  },
];

// Compatibility export for Vitest configuration and tooling that need the
// complete root-suite membership rather than its resource schedule.
export const testFiles = rootVitestSuites.flatMap((suite) => suite.files);
